export const server_dev_url = "http://localhost:9000/api";
export const server_production_url = "https://cbt-api-dl3h.onrender.com/api";
export const Roles = { ADMIN: "Admin", LECTURER: "Lecturer", STUDENT: "Student" };

export const cbt_url = {
    home: "/",
    dashboard: "/dashboard",
    colleges: "/colleges",
    departments: "/departments",
    courses: "/courses",
    course: "/course",
    lecturerCourses: "/courses/lecturer",
    exams: "/exams",
    exam: "/exam",
    setEaxm: "/exam/create/",
    students: "/students",
    student: "/student",
    staffs: "/staffs",
    staff: "/staff",
    startExam: "/exam/start",
    submittedExam: "/exam/submitted",
    studentExams: "/student/exams",
    examResult: "/exam/results",
    studentResult: "/student/exam/results",
    profile: "/profile",
    login: "/login",
    studentLogin: "/login/student",
    staffLogin: "/login/staff",
    staffRegistration: "/register/staff",
    studentRegistration: "/register/student",
    updateStaff: "/update/staff/:id",
    updateStudent: "/update/student/:id",
    createCourse: "/course/create",
    createDepartment: "/department/create",
    createCollege: "/college/create",
    updateCourse: "/course/update",
    updateDepartment: "/department/update",
    updateCollege: "/college/update",
}