export const server_dev_url = "http://localhost:9000/apai";
export const Roles = { ADMIN: "Admin", LECTURER: "Lecturer", STUDENT: "Student" };

export const cbt_url = {
    home: "/",
    dashboard: "/dashboard",
    colleges: "/colleges",
    departments: "/departments",
    courses: "/courses",
    exams: "/exams",
    exam: "/exam",
    students: "/students",
    staffs: "/staffs",
    startExam: "/exam/start",
    submittedExam: "/exam/submitted",
    studentExams: "/student/exams",
    examResult: "/exam/results",
    studentResult: "/student/exam/results",
    profile: "/profile",
    login: "/login",
    studentLogin: "/login/student",
    staffLogin: "/login/staff",
    staffRegistration: "/register/staff",
    studentRegistration: "/register/student",
    updateStaff: "/update/staff/:id",
    updateStudent: "/update/student/:id",
    createCourse: "/course/create",
    createDepartment: "/department/create",
    createCollege: "/college/create",
    updateCourse: "/course/update",
    updateDepartment: "/department/update",
    updateCollege: "/college/update",
}